schema_version = "1.0.0"

blender_version_min = "4.5.0"
id = "MaterialHelper"
license = ["SPDX:GPL-3.0-or-later", ]
maintainer = "ACGGIT社区, Atticus, 小萌新"
name = "MaterialHelper"
tagline = "Make local asset manager your place to create powerful materials"
type = "add-on"
version = "1.4.5"
tags = ["3D View", "Material"]

[permissions]
files = "Load preview material file/Accessing and mofying asset catalog file"
