data = {
    "Edit Material Asset": "编辑材质资产",
    "Apply Selected as True Assets": "应用选定项为真资产",
    "Clear Asset": "清除资产",
    "Clear Asset (Set Fake User)": "清除资产 (设置伪用户)",
    "Clear Asset (Delete)": "清除资产 (删除)",
    "Update Material Asset Preview": "更新材质资产预览",
    "Add Material": "添加材质",
    "Material Window": "材质窗口",
    "Follow Material": "跟随材质",
    "Show UI Panel": "显示侧面板",
    "UI Panel Direction": "侧面板方向",
    "Big Window": "大窗口",
    "Small Window": "小窗口",
    "Realtime Preview": "实时预览",
    "Rename Active Item": "重命名活动项",
    "Duplicate Active Item": "复制活动项",
    "Delete Selected Materials": "删除选中材质",
    "Align Dependence": "对齐子节点",
    "Align Dependence Nodes": "对齐子节点",
    "Move Dependence": "移动子节点/父节点",
    "Node Distance X": "节点间距X",
    "Node Distance Y": "节点间距Y",
    "Auto Update": "自动更新",
    "Object / Material Select Sync": "物体/材质选择同步",
    "Clear Unused Material": "清理未用材质",
    "If checked, the active object's materials will be automatically selected": "如果勾选，激活物体材质将被自动选中",
    "If checked, the material will be automatically add as temp asset\nElse, temp assets will be cleared": "如果勾选，材质将自动添加为临时资产\n否则，临时资产将被清除",
    "Material Helper": "材质助手",
    "Replace Material": "替换材质",
    "Replace Selected Material to...": "替换选中材质为...",
    "Manual Refresh": "手动刷新",
    'Refresh Preview': '刷新预览',
}
