data = {
    "Edit Material Asset": "编辑材质资产",
    "Apply Selected as True Assets": "应用选定项为真资产",
    "Clear Asset": "清除资产",
    "Clear Asset (Set Fake User)": "清除资产 (设置伪用户)",
    "Clear Asset (Delete)": "清除资产 (删除)",
    "Update Material Asset Preview": "更新材质资产预览",
    "Add Material": "添加材质",
    "Material Window": "材质窗口",
    "Follow Material": "跟随材质",
    "Show UI Panel": "显示侧面板",
    "UI Panel Direction": "侧面板方向",
    "Big Window": "大窗口",
    "Small Window": "小窗口",
    "Realtime Preview(If enable and open more than 15 window will crash blender)": "实时预览(如果启用并打开超过15个窗口将会崩溃)",
    "Rename Active Item": "重命名活动项",
    "Duplicate Active Item": "复制活动项",
    "Delete Selected Materials": "删除选中材质",
    "Align Dependence": "对齐子节点",
    "Align Dependence Nodes": "对齐子节点",
    "Move Dependence": "移动子节点/父节点",
    "Node Distance X": "节点间距X",
    "Node Distance Y": "节点间距Y",
    "Auto Update": "自动更新",
    "Object / Material Select Sync": "物体/材质选择同步",
    "Clear Unused Material": "清理未用材质",
    "If checked, the active object's materials will be automatically selected": "如果勾选，激活物体材质将被自动选中",
    "If checked, the material will be automatically add as temp asset\nElse, temp assets will be cleared": "如果勾选，材质将自动添加为临时资产\n否则，临时资产将被清除",
    "Material Helper": "材质助手",
    "Replace Material": "替换材质",
    "Replace Selected Material to...": "替换选中材质为...",
    "Manual Refresh": "手动刷新",
    'Refresh Preview': '刷新预览',
    'Select Material Object': '选择材质物体',
    "Make the local asset manager your place to create powerful materials": "将本地资产管理器作为你创造强大材质的地方吧",
    "{} is set as True Asset": "{}设置为真实资产",
    "Select Sync": "选择同步",
    "Realtime Preview": "实时预览",
    "Full Screen": "全屏",
    "Contract the window": "缩小窗口",
    "Switch window": "切换窗口",
    "Close Window": "关闭窗口",
    "Window Style": "窗口样式",
    "Preview Material Window Style": "预览材质窗口样式",
    "Apply as asset": "应用为资产",
    "Convert temporary assets into regular assets": "将临时资产转换为固定资产",
    "Shader Ball": "着色球",
    "Preview Render Type": "预渲染类型",
    "Load preview material file": "加载预览材质文件",
    "Blender performance limitations: Too many partial views, cannot exceed 16": "Blender性能限制: 部视图过多,无法超过16个",
    "Please select a local material asset": "请选择一个本地材质资产",
    "Please close the preview window before proceeding with the operation": "请关闭预览窗口后再进行操作",

    "Carpaint": "汽车漆",
    "Emission": "自发光",
    "Glass": "玻璃",
    "Metal": "金属",
    "Plastic": "塑料",
    "Picker material(Material Helper)": "拾取材质(材质助手)",

    "%s is pick sort to last": "%s 已被拾取,重新排序",
    "Please pick materials through the header button": "请通过标题栏按钮拾取材质",
    "Material not picked up": "未拾取材质",
    "Picker material: %i": "拾取材质: %i",
    "Ctrl:Continuous pick    Alt:Pick object all material": "Ctrl:连续拾取  Alt:拾取物体所有材质",
    "Ctrl:Continuous assign material    Alt:Assign object material": "Ctrl:连续赋予材质  Alt:赋予整个物体材质",
    "Material picker panel": "材质拾取面板",
    "Preview Scale": "预览缩放",
    "Ctrl:Continuous assign material": "Ctrl:连续赋予材质",
    "Continuous picker material": "连续拾取材质",
    "Ctrl:Continuous picker material": "Ctrl:连续拾取材质",
    "Ctrl:Continuous picker material\nShift:Picker the materials of all selected objects": "Ctrl:连续拾取材质\nShift:拾取选择物体所有材质",
    "Shift: Picker the materials of all selected objects": "Shift: 拾取选择物体所有材质",
    "Ctrl: Pick all material in asset": "Ctrl: 拾取所有资产材质",
    "Picker Material": "拾取材质",
    "%i materials have been picker": "%i个材质已被拾取",
    "Picker the materials of all selected objects": "拾取选择物体所有材质",
    "Material assigned to %i objects": "材质被赋予到%i个物体",
    "Shift:Assign the materials of all selected objects": "Shift:材质赋予到所有选择的物体",
    "Alt:Assign a selection face": "Alt:赋予到所选面",
    "Assign material": "赋予材质",
    "Material board": "材质板",
    "Assign picker material to %s -> %i": "赋予拾取材质到 %s -> %i",
    "Assign picker material to %i objects %s": "赋予拾取材质到%i个物体 %s",
    "Assign material to %i objects %s": "赋予拾取材质到%i个物体 %s",
    "Drag material": "拖动材质",
    "Not picker material": "未拾取材质",
    "Material slot": "材质槽",
    "Replace material": "替换材质",
    "Clear material board": "清空材质板",
    "Alt: Pick all materials in the scene": "Alt: 拾取场景中的所有材质",
    "Assign object material": "分配物休材质",
    "Continuous assign material": "连续分配材质",
    "3D View Generic": "3D视图通用",
    "Assign material by modal": "赋予材质按模态"
}
